#!/usr/bin/env sh

changedFiles=$(echo `git diff --name-only --cached --pretty -r`)

changedComponent=$(echo $changedFiles | grep -Eo "Component/")
changedComponents=$(echo $changedFiles | grep -o "components/")
changedElem=$(echo $changedFiles | grep -Eo "Elem/")
changedStyled=$(echo $changedFiles | grep -Eo "styled/")
changedUtils=$(echo $changedFiles | grep -o "utils/")

echo $changedFiles

if [ "$changedComponent" != "" ]; then
	bun test Component || exit 1
fi

if [ "$changedComponents" != "" ]; then
	bun test components || exit 1
	bun run build:types || exit 1
fi

if [ "$changedElem" != "" ]; then
	bun test Elem || exit 1
fi

if [ "$changedStyled" != "" ]; then
	bun test styled || exit 1
fi

if [ "$changedUtils" != "" ]; then
	bun test utils || exit 1
fi

bun run format || exit 1