export const paths = {
	button: '/Button',
	colorPicker: '/ColorPicker',
	dialog: '/Dialog',
	domElem: '/DomElem',
	iconButton: '/IconButton',
	label: '/Label',
	link: '/Link',
	menu: '/Menu',
	modal: '/Modal',
	noData: '/NoData',
	numberInput: '/NumberInput',
	popover: '/Popover',
	search: '/Search',
	select: '/Select',
	tag: '/Tag',
	tagList: '/TagList',
	textarea: '/Textarea',
	textInput: '/TextInput',
};
