import { readdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

import { extractJSDoc } from './extractJSDoc.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const GENERATED_START = '// ── GENERATED: Built-in components ────────────────────────────────────────────';
const GENERATED_END = '// ── END GENERATED ────────────────────────────────────────────────────────────';

/**
 * Convert a JSDoc type string (e.g. `{string|Function}`) to a TypeScript type string.
 * @param {string} type - Raw JSDoc type including surrounding braces
 * @returns {string} TypeScript-compatible type string
 */
function jsDocTypeToTS(type) {
	if (!type) return 'any';

	return type
		.trim()
		.replace(/^\{|\}$/g, '')
		.replace(/\*/g, 'any')
		.replace(/\bFunction\b/g, '(...args: any[]) => any')
		.replace(/\bobject\b/g, 'Record<string, any>')
		.replace(/\bArray\b(?!<)/g, 'Array<any>')
		.replace(/\|/g, ' | ')
		.replace(/\s{2,}/g, ' ')
		.trim();
}

const COMPONENT_OPTIONS_KEYS = new Set([
	'tag',
	'autoRender',
	'registeredEvents',
	'knownAttributes',
	'priorityOptions',
	'styles',
	'uniqueId',
	'style',
	'attributes',
	'className',
	'id',
	'textContent',
	'innerText',
	'innerHTML',
	'content',
	'appendTo',
	'prependTo',
	'append',
	'prepend',
	'before',
	'disabled',
	'onclick',
	'onConnected',
	'onDisconnected',
	'onRendered',
	'onPointerPress',
	'onHover',
	'onPointerOver',
	'onPointerEnter',
	'onPointerDown',
	'onPointerMove',
	'onPointerUp',
	'onPointerLeave',
	'onPointerCancel',
	'onContextmenu',
	'onChange',
	'onKeydown',
	'onKeyup',
	'onInput',
	'onBlur',
	'onSearch',
	'addClass',
]);

/**
 * Generate TypeScript interface and class declaration for a single component from its JSDoc.
 * @param {string} name - Component class name (e.g. "Button")
 * @param {object} jsDoc - Parsed JSDoc object from extractJSDoc
 * @returns {string} TypeScript declaration block
 */
function generateComponentInterface(name, jsDoc) {
	const lines = [];
	const componentOptions = jsDoc.options.filter(
		opt => (opt.name !== 'options' || opt.isSubProperty) && !COMPONENT_OPTIONS_KEYS.has(opt.name),
	);
	const methods = jsDoc.methods.filter(m => !m.name.startsWith('_'));

	if (componentOptions.length > 0) {
		lines.push(`export interface ${name}Options extends ComponentOptions {`);
		for (const opt of componentOptions) {
			const tsType = jsDocTypeToTS(opt.type);
			if (opt.description) lines.push(`\t/** ${opt.description} */`);
			lines.push(`\t${opt.name}?: ${tsType};`);
		}
		lines.push('}');
		lines.push('');
	}

	const getters = jsDoc.properties.filter(p => p.access === 'readonly' && p.type !== 'unknown');

	const optionsType = componentOptions.length > 0 ? `${name}Options` : 'ComponentOptions';
	lines.push(`export declare class ${name} extends Component {`);
	lines.push(`\tconstructor(options?: ${optionsType}, ...children: Array<Elem | HTMLElement | string>);`);

	for (const getter of getters) {
		const tsType = jsDocTypeToTS(`{${getter.type}}`);
		if (getter.description) lines.push(`\t/** ${getter.description} */`);
		lines.push(`\treadonly ${getter.name}: ${tsType};`);
	}

	for (const method of methods) {
		const params = method.parameters.map(p => `${p.name}${p.optional ? '?' : ''}: ${jsDocTypeToTS(p.type)}`).join(', ');
		const ret = method.returns ? jsDocTypeToTS(method.returns.type) : 'void';
		if (method.description) lines.push(`\t/** ${method.description} */`);
		lines.push(`\t${method.name}(${params}): ${ret};`);
	}

	lines.push('}');
	lines.push('');

	return lines.join('\n');
}

/**
 * Scan the components directory and build the generated type declaration block.
 * @returns {{ block: string, count: number }} Generated TS source and component count
 */
function buildComponentTypes() {
	const componentsDir = join(root, 'components');
	const dirs = readdirSync(componentsDir, { withFileTypes: true })
		.filter(d => d.isDirectory())
		.map(d => d.name)
		.sort();

	const generated = [
		GENERATED_START,
		'// This section is generated by devTools/buildTypes.js — do not edit manually.',
		'// Run `bun run build:types` to regenerate from JSDoc annotations.',
		'',
	];

	for (const dir of dirs) {
		const componentFile = join(componentsDir, dir, `${dir}.js`);
		if (!existsSync(componentFile)) continue;

		generated.push(generateComponentInterface(dir, extractJSDoc(componentFile)));
	}

	generated.push(GENERATED_END);

	return { block: generated.join('\n'), count: dirs.length };
}

/**
 * Read index.d.ts, replace the generated component block, and write it back.
 */
function updateIndexDts() {
	const indexDtsPath = join(root, 'index.d.ts');
	const content = readFileSync(indexDtsPath, 'utf8');
	const { block, count } = buildComponentTypes();

	let updated;
	if (content.includes(GENERATED_START) && content.includes(GENERATED_END)) {
		const start = content.indexOf(GENERATED_START);
		const end = content.indexOf(GENERATED_END) + GENERATED_END.length;
		updated = content.slice(0, start) + block + content.slice(end);
	} else {
		const builtInMarker = '// ── Built-in components ──';
		const markerIndex = content.indexOf(builtInMarker);
		updated =
			markerIndex !== -1 ? content.slice(0, markerIndex) + block + '\n' : content.trimEnd() + '\n\n' + block + '\n';
	}

	writeFileSync(indexDtsPath, updated, 'utf8');
	console.log(`✓ index.d.ts updated — ${count} components`);
}

updateIndexDts();
